### ISSUE TITLE
App Crashes when Converting Switch - PC save

### ISSUE THREAD

**Issue by HaroPla** [AsteriskAmpersand/MHST2-Save-Tools#3]
The app crashes when I click "Convert" when converting Switch save to PC save.

**Comment by iSharingan** [comment]
you likely either checked "convert to Switch" and/or forgot to specify an output file (those are the only two instances I could get get a crash).

That said, Asterisk, it would probably be wise to error catch the lack of an output file and append a string to the original file name (IE: mhr_slot_1.sav would make the output file mhr_slot_1**_SWconvert**.sav or mhr_slot_1**_Decrypted**.sav or mhr_slot_1**_Steam_ID_[input ID]**.sav depending on option selected

**Comment by lileihai** [comment]
That does happens both in 'Pc to Pc'  and  'switch to pc' Converting.After unchecked "convert to Switch" and specify an output file,it still crashed!

**Comment by iSharingan** [comment]
You're probably misding the second executable. Make sure both AAStories2SaveTool.exe and AndoStories2Tool.exe are in the same folder.

**Comment by lileihai** [comment]
peoblem solved thx!
