### ISSUE TITLE
Save is Corrupted

### ISSUE THREAD

**Issue by Zemeria** [AsteriskAmpersand/MHST2-Save-Tools#5]
When converting from Switch to PC it starts up and goes to load data and then says that it is corrupted and must be deleted to continue playing. I havent updated my switch version due to lack of net so wondering if thats causing an issue. Otherwise im unsure why. Though I did use the MHS2 save editor could that have done it?

**Comment by shenqing1254** [comment]
Thank you very much for your sharing, but after I tried countless kinds of operation from PC to switch, I can't read the archived data all the time. Are you sure that the operation is only convert to switch and convert?

**Comment by lileihai** [comment]
> Thank you very much for your sharing, but after I tried countless kinds of operation from PC to switch, I can't read the archived data all the time. Are you sure that the operation is only convert to switch and convert?

After pc to switch converting,You still need to use software like UltraEdit to open the achived savedata file to change first byte from 00 to 01 to make it work,hoping they will fix it in next edition.

**Comment by Zemeria** [comment]
Might be a little confused. I am trying to go from Switch > PC and the PC version is saying its corrupt

**Comment by phuongpham2011** [comment]
please help me, when i open AndoStories2Tool.exe it shows this cmd panel, after few seconds it will turn itself off
https://user-images.githubusercontent.com/68677816/126047092-61295176-6e25-41a1-8534-60e6e51d80db.png

**Comment by lileihai** [comment]
> please help me, when i open AndoStories2Tool.exe it shows this cmd panel, after few seconds it will turn itself off
> https://user-images.githubusercontent.com/68677816/126047092-61295176-6e25-41a1-8534-60e6e51d80db.png

Download  AAStories2SaveTool.exe and AndoStories2Tool.exe. Make sure both AAStories2SaveTool.exe and AndoStories2Tool.exe are in the same folder.Use AStories2SaveTool.exe to convert.

**Comment by phuongpham2011** [comment]
> > please help me, when i open AndoStories2Tool.exe it shows this cmd panel, after few seconds it will turn itself off
> > https://user-images.githubusercontent.com/68677816/126047092-61295176-6e25-41a1-8534-60e6e51d80db.png
> 
> Download AAStories2SaveTool.exe and AndoStories2Tool.exe. Make sure both AAStories2SaveTool.exe and AndoStories2Tool.exe are in the same folder.Use AStories2SaveTool.exe to convert.

thanks, i made it

**Comment by darkphoenix7794** [comment]
I have the same issue as the save data being corrupted but I am **not converting from PC>SWITCH or SWITCH>PC**. I am **ONLY** playing the MHS2 game on **PC/Laptop**.

My MHS2 game is not installed via Steam but I downloaded the from https://dodi-repacks.site/1380-monster-hunter-stories-2-wings-of-ruin-deluxe-edition-v1-5-3-all-dlcs-multi13-dodi-repack/

Please anyone I badly need your help.
