### ISSUE TITLE
Crashes when Converting Switch > PC

### ISSUE THREAD

**Issue by DirtyRiq** [AsteriskAmpersand/MHST2-Save-Tools#6]
I have no problem converting my PC save file to Switch, but when attempting to convert back the program crashes. I am unsure if I am doing something wrong or if it is an issue with the program.

**Comment by daveysha** [comment]
I have the same problem too

**Comment by lileihai** [comment]
> I have no problem converting my PC save file to Switch, but when attempting to convert back the program crashes. I am unsure if I am doing something wrong or if it is an issue with the program.

You're probably missing the second executable. Make sure both AAStories2SaveTool.exe and AndoStories2Tool.exe are in the same folder.

**Comment by DirtyRiq** [comment]
> > I have no problem converting my PC save file to Switch, but when attempting to convert back the program crashes. I am unsure if I am doing something wrong or if it is an issue with the program.
> 
> You're probably missing the second executable. Make sure both AAStories2SaveTool.exe and AndoStories2Tool.exe are in the same folder.

They are, I am still having the crashing issue

**Comment by DirtyRiq** [comment]
> > I have no problem converting my PC save file to Switch, but when attempting to convert back the program crashes. I am unsure if I am doing something wrong or if it is an issue with the program.
> 
> You're probably missing the second executable. Make sure both AAStories2SaveTool.exe and AndoStories2Tool.exe are in the same folder.

Should I be able to run AndoStories2Tool.exe on its own? When I try to load that I get errors about multiple missing .dll files.
Sorry, I am not the most tech savvy person, I know the crashing is most likely an error on my part but I don't know where to start, only thing I have to go off is the guide Asterisk posted.

**Comment by lileihai** [comment]
> > > I have no problem converting my PC save file to Switch, but when attempting to convert back the program crashes. I am unsure if I am doing something wrong or if it is an issue with the program.
> > 
> > 
> > You're probably missing the second executable. Make sure both AAStories2SaveTool.exe and AndoStories2Tool.exe are in the same folder.
> 
> Should I be able to run AndoStories2Tool.exe on its own? When I try to load that I get errors about multiple missing .dll files.
> Sorry, I am not the most tech savvy person, I know the crashing is most likely an error on my part but I don't know where to start, only thing I have to go off is the guide Asterisk posted.

only download AAStories2SaveTool.exe and AndoStories2Tool.exe here :https://github.com/AsteriskAmpersand/MHST2-Save-Tools/releases/tag/1.2 .when you run AndoStories2Tool.exe on its own,it should pop a window like this :https://user-images.githubusercontent.com/68677816/126047092-61295176-6e25-41a1-8534-60e6e51d80db.png and disappear soon.

**Comment by DirtyRiq** [comment]
> > > > I have no problem converting my PC save file to Switch, but when attempting to convert back the program crashes. I am unsure if I am doing something wrong or if it is an issue with the program.
> > > 
> > > 
> > > You're probably missing the second executable. Make sure both AAStories2SaveTool.exe and AndoStories2Tool.exe are in the same folder.
> > 
> > 
> > Should I be able to run AndoStories2Tool.exe on its own? When I try to load that I get errors about multiple missing .dll files.
> > Sorry, I am not the most tech savvy person, I know the crashing is most likely an error on my part but I don't know where to start, only thing I have to go off is the guide Asterisk posted.
> 
> only download AAStories2SaveTool.exe and AndoStories2Tool.exe here :https://github.com/AsteriskAmpersand/MHST2-Save-Tools/releases/tag/1.2 and make sure they are in the same folder .when you run AndoStories2Tool.exe on its own,it should pop a window like this :https://user-images.githubusercontent.com/68677816/126047092-61295176-6e25-41a1-8534-60e6e51d80db.png and disappear soon.

It does not do that when I try to run Ando, instead this is popping up along with a few other missing .dll file messages
![Error](https://user-images.githubusercontent.com/87586567/126054883-773cd344-a840-48de-8732-771882269912.png)

I am assuming that is the source of my issue but I'm not sure how to fix this.

**Comment by lileihai** [comment]
> > > > > I have no problem converting my PC save file to Switch, but when attempting to convert back the program crashes. I am unsure if I am doing something wrong or if it is an issue with the program.
> > > > 
> > > > 
> > > > You're probably missing the second executable. Make sure both AAStories2SaveTool.exe and AndoStories2Tool.exe are in the same folder.
> > > 
> > > 
> > > Should I be able to run AndoStories2Tool.exe on its own? When I try to load that I get errors about multiple missing .dll files.
> > > Sorry, I am not the most tech savvy person, I know the crashing is most likely an error on my part but I don't know where to start, only thing I have to go off is the guide Asterisk posted.
> > 
> > 
> > only download AAStories2SaveTool.exe and AndoStories2Tool.exe here :https://github.com/AsteriskAmpersand/MHST2-Save-Tools/releases/tag/1.2 and make sure they are in the same folder .when you run AndoStories2Tool.exe on its own,it should pop a window like this :https://user-images.githubusercontent.com/68677816/126047092-61295176-6e25-41a1-8534-60e6e51d80db.png and disappear soon.
> 
> It does not do that when I try to run Ando, instead this is popping up along with a few other missing .dll file messages
> ![Error](https://user-images.githubusercontent.com/87586567/126054883-773cd344-a840-48de-8732-771882269912.png)
> 
> I am assuming that is the source of my issue but I'm not sure how to fix this.

Download and install vc 2015~2019 support and try it again.https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by lileihai** [comment]
> > > > > > I have no problem converting my PC save file to Switch, but when attempting to convert back the program crashes. I am unsure if I am doing something wrong or if it is an issue with the program.
> > > > > 
> > > > > 
> > > > > You're probably missing the second executable. Make sure both AAStories2SaveTool.exe and AndoStories2Tool.exe are in the same folder.
> > > > 
> > > > 
> > > > Should I be able to run AndoStories2Tool.exe on its own? When I try to load that I get errors about multiple missing .dll files.
> > > > Sorry, I am not the most tech savvy person, I know the crashing is most likely an error on my part but I don't know where to start, only thing I have to go off is the guide Asterisk posted.
> > > 
> > > 
> > > only download AAStories2SaveTool.exe and AndoStories2Tool.exe here :https://github.com/AsteriskAmpersand/MHST2-Save-Tools/releases/tag/1.2 and make sure they are in the same folder .when you run AndoStories2Tool.exe on its own,it should pop a window like this :https://user-images.githubusercontent.com/68677816/126047092-61295176-6e25-41a1-8534-60e6e51d80db.png and disappear soon.
> > 
> > 
> > It does not do that when I try to run Ando, instead this is popping up along with a few other missing .dll file messages
> > ![Error](https://user-images.githubusercontent.com/87586567/126054883-773cd344-a840-48de-8732-771882269912.png)
> > I am assuming that is the source of my issue but I'm not sure how to fix this.
> 
> Don't download the sourceCode(zip),directly download AAStories2SaveTool.exe and AndoStories2Tool.exe!
> ![捕获](https://user-images.githubusercontent.com/87460002/126056747-ec168e76-3be6-4976-bc6f-2e477878659f.PNG)

If that happens again,you may install vc 2015~2019:https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by daveysha** [comment]
I got it working thank you for your help this was frustrating me .

**Comment by DirtyRiq** [comment]
> > > > > > > I have no problem converting my PC save file to Switch, but when attempting to convert back the program crashes. I am unsure if I am doing something wrong or if it is an issue with the program.
> > > > > > 
> > > > > > 
> > > > > > You're probably missing the second executable. Make sure both AAStories2SaveTool.exe and AndoStories2Tool.exe are in the same folder.
> > > > > 
> > > > > 
> > > > > Should I be able to run AndoStories2Tool.exe on its own? When I try to load that I get errors about multiple missing .dll files.
> > > > > Sorry, I am not the most tech savvy person, I know the crashing is most likely an error on my part but I don't know where to start, only thing I have to go off is the guide Asterisk posted.
> > > > 
> > > > 
> > > > only download AAStories2SaveTool.exe and AndoStories2Tool.exe here :https://github.com/AsteriskAmpersand/MHST2-Save-Tools/releases/tag/1.2 and make sure they are in the same folder .when you run AndoStories2Tool.exe on its own,it should pop a window like this :https://user-images.githubusercontent.com/68677816/126047092-61295176-6e25-41a1-8534-60e6e51d80db.png and disappear soon.
> > > 
> > > 
> > > It does not do that when I try to run Ando, instead this is popping up along with a few other missing .dll file messages
> > > ![Error](https://user-images.githubusercontent.com/87586567/126054883-773cd344-a840-48de-8732-771882269912.png)
> > > I am assuming that is the source of my issue but I'm not sure how to fix this.
> > 
> > 
> > Don't download the sourceCode(zip),directly download AAStories2SaveTool.exe and AndoStories2Tool.exe!
> > ![捕获](https://user-images.githubusercontent.com/87460002/126056747-ec168e76-3be6-4976-bc6f-2e477878659f.PNG)
> 
> If that happens again,you may install vc 2015~2019:https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
